### ISSUE TITLE
Failed Verification Test - testGetExternalLinkDomain

### ISSUE THREAD

**Issue by rpg32** [HDFGroup/h5serv#120]
I just installed 5hserv on Windows 10 using Conda. After running the 'testall.py' script everything passes except for the last test. This was the error:

FAIL: testGetExternalLinkDomain (__main__.LinkTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "linktest.py", line 129, in testGetExternalLinkDomain
    self.assertEqual(h5domain, expected_curdir)
AssertionError: u'tall.C:%5CUsers%5CRobert.Geiger%5CPrograms%5Ch5serv%5Cdata%5Ctest.test.hdfgroup.org' != 'tall.test.hdfgroup.org'
----------------------------------------------------------------------

Thanks in advance!

**Comment by pozsa** [comment]
This test fails for me as well.
My docker-compose file:
```
version: "3.7"

services:
  hdf5:
    container_name: hdf5
    image: hdfgroup/h5serv:latest
    restart: always
    volumes:
      - ./hdf5/data:/data
      #- ./hdf5/passwd.h5:/usr/local/src/h5serv/util/admin/passwd.h5
    ports:
      - 5000:5000
```

Step into container:
```bash
docker exec -it hdf5 bash
```

Within container:
```bash
cd /usr/local/src/h5serv/test
python testall.py
```

Failed test notification:
```
linktest
....F..............
======================================================================
FAIL: testGetExternalLinkDomain (__main__.LinkTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "linktest.py", line 129, in testGetExternalLinkDomain
    self.assertEqual(h5domain, expected_curdir)
AssertionError: 'tall.test.data.h5serv.src.local.usr.hdfgroup.org' != 'tall.test.hdfgroup.org'
- tall.test.data.h5serv.src.local.usr.hdfgroup.org
+ tall.test.hdfgroup.org


----------------------------------------------------------------------
Ran 19 tests in 1.588s

FAILED (failures=1)
Failed
root@97959a55ca16:/usr/local/src/h5serv/test# 
```
