### ISSUE TITLE
jsontoh5.py can't produce HDF5 file.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/h5serv#39]
I created a simple JSON file based on this:
http://hdf5-json.readthedocs.org/en/latest/examples/objref_attr.html

I get the following error when I tried to create HDF5:

```
python jsontoh5.py ~/src/hpd/objref.json objref.h5
Traceback (most recent call last):
  File "jsontoh5.py", line 247, in <module>
    main()
  File "jsontoh5.py", line 235, in main
    h5writer.writeFile() 
  File "jsontoh5.py", line 208, in writeFile
    self.createObjects()    # create datasets, groups, committed datatypes
  File "jsontoh5.py", line 151, in createObjects
    self.createDataset(uuid, json_obj)
  File "jsontoh5.py", line 89, in createDataset
    obj_uuid=uuid)
  File "../server/hdf5db.py", line 1125, in createDataset
    maxshape=max_shape, fillvalue=fill_value)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/h5py/_hl/group.py", line 99, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 55, in make_new_dset
    raise TypeError("Either data or shape must be specified")
TypeError: Either data or shape must be specified
```

**Comment by jreadey** [comment]
This was failing because PUT on attributes with obj reference type was not supported.  This is implemented now for attributes and datasets.  Json above converts to h5 correctly.

**Comment by hyoklee** [comment]
I got the following error on dimscale.json:

```
[ec2-user@ip-172-31-15-26 util]$ python jsontoh5.py dimscale.json dimscale.h5
creating group: 75ccaaea-f3e2-4f22-a4ea-b48d2e93581e
creating dataset:  6f7557ae-7394-4e7d-b502-be8b7f2ed823
creating dataset:  837dc7ef-bf64-44e4-8982-798d669cc822
creating dataset:  f4fd3700-b22b-45e0-b2e8-75c73824b691
creating Attribute: CLASS  in uuid: 6f7557ae-7394-4e7d-b502-be8b7f2ed823
creating Attribute: units  in uuid: 6f7557ae-7394-4e7d-b502-be8b7f2ed823
creating Attribute: standard_name  in uuid: 6f7557ae-7394-4e7d-b502-be8b7f2ed823
creating Attribute: REFERENCE_LIST  in uuid: 6f7557ae-7394-4e7d-b502-be8b7f2ed823
  File "h5tojson.py", line 236, in <module>
    main()
  File "h5tojson.py", line 231, in main
    with Hdf5db(filename, dbFilePath=dbFilename, readonly=True, app_logger=log) as db:
  File "../server/hdf5db.py", line 108, in __init__
    self.f = h5py.File(filePath, mode)
  File "/home/ec2-user/anaconda/lib/python2.7/site-packages/h5py/_hl/files.py", line 222, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/home/ec2-user/anaconda/lib/python2.7/site-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:1741)
IOError: Unable to open file (Unable to find a valid file signature)
```

**Comment by hyoklee** [comment]
I updated dim scale.json according to https://github.com/HDFGroup/hpd/issues/7 and https://github.com/HDFGroup/hpd/issues/9 but I still get a different error:

```
creating group: 2bb4d338-cfb1-4650-8a97-4c80e90a3343
creating dataset:  a169935a-8362-4bbf-9372-8b01801c7fe5
creating dataset:  7166a394-ad05-405b-beaf-f01642f82179
creating dataset:  dc1b97d0-6303-4daf-b461-3c7be5dd8199
creating Attribute: CLASS  in uuid: a169935a-8362-4bbf-9372-8b01801c7fe5
creating Attribute: units  in uuid: a169935a-8362-4bbf-9372-8b01801c7fe5
creating Attribute: standard_name  in uuid: a169935a-8362-4bbf-9372-8b01801c7fe5
creating Attribute: REFERENCE_LIST  in uuid: a169935a-8362-4bbf-9372-8b01801c7fe5
Traceback (most recent call last):
  File "jsontoh5.py", line 254, in <module>
    main()
  File "jsontoh5.py", line 242, in main
    h5writer.writeFile() 
  File "jsontoh5.py", line 216, in writeFile
    self.createAttributes() # create attributes for objects
  File "jsontoh5.py", line 193, in createAttributes
    self.createAttribute(attribute, "datasets", uuid)
  File "jsontoh5.py", line 119, in createAttribute
    self.db.createAttribute(col_name, uuid, attr_name, dims, datatype, attr_value)
  File "../server/hdf5db.py", line 882, in createAttribute
    obj.attrs.create(attr_name, value, dtype=dt)
  File "/home/ec2-user/anaconda/lib/python2.7/site-packages/h5py/_hl/attrs.py", line 93, in create
    data = numpy.asarray(data, order='C', dtype=dtype)
  File "/home/ec2-user/anaconda/lib/python2.7/site-packages/numpy/core/numeric.py", line 460, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: Setting void-array with object members using buffer.
```

**Comment by ajelenak-thg** [comment]
> ValueError: Setting void-array with object members using buffer.

I confirm this error. I updated PD server's JSON to HDF5 template code and got the same error.

**Comment by jreadey** [comment]
I'm having problems creating attributes with VLEN data type and a Obj Reference base. Is this an hypy issue?  Does anyone see what's wrong with this test code:

import h5py
import numpy as np
f = h5py.File("myvelref.h5", "w")
dset = f.create_dataset('d1', (4,), dtype='f')
refdt = h5py.special_dtype(ref=h5py.Reference)
vlendt = h5py.special_dtype(vlen=refdt)
vlen_elem = ( dset.ref, )
data = ( vlen_elem, )
f.attrs.create("myvlenref", data, shape=(1,), dtype=vlendt)
f.close()

It gives an error: 'h5py.h5r.Reference' object has no attribute 'dtype'

**Comment by hyoklee** [comment]
How about asking it to @andrewcollette?

**Comment by jreadey** [comment]
Yes, I've posted it here: https://github.com/h5py/h5py/issues/553#issuecomment-83132116

**Comment by jreadey** [comment]
Andrew doesn't have any immediate ideas on this.  
Joe, can you define a dimscale.json that doesn't use the VLEN data with REFERENCE type?  (is VLEN data part of the dimscale spec?)

**Comment by ajelenak-thg** [comment]
We can always use the dimension scale API.

**Comment by hyoklee** [comment]
I'm not an expert of dim scale. I hope @kyang2014 can help us.

@ajelenak-thg,  can you demo the use of dim. scale. APIs with your HPD server's jsontoh5 while John is working on low-level solution?

**Comment by jreadey** [comment]
I've got a sample output of jsontoh5.py with dim_scale.json.  I'll send you guys the files.

**Comment by jreadey** [comment]
File output has been validated, so closing this issue.
