### ISSUE TITLE
I can't create HDF5 file from a JSON that was produced by HPD Server.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/h5serv#42]
I put the JSON file on EC2 for your quick testing.

The below is the error message:
```
[ec2-user@ip-172-31-15-26 util]$ python jsontoh5.py hmap_100.json hmap_100.h5
Traceback (most recent call last):
  File "jsontoh5.py", line 252, in <module>
    main()
  File "jsontoh5.py", line 240, in main
    h5writer.writeFile()
  File "jsontoh5.py", line 214, in writeFile
    self.createAttributes() # create attributes for objects
  File "jsontoh5.py", line 182, in createAttributes
    self.createAttribute(attribute, "groups", uuid)
  File "jsontoh5.py", line 118, in createAttribute
    self.db.createAttribute(col_name, uuid, attr_name, dims, datatype, attr_value)
  File "../server/hdf5db.py", line 822, in createAttribute
    dt = self.createTypeFromItem(attr_type)
  File "../server/hdf5db.py", line 579, in createTypeFromItem
    raise IOError(errno.EINVAL, msg)
IOError: [Errno 22] Unable able to create type: 'strsize' not provided
```

**Comment by jreadey** [comment]
Problem is with the string type attributes.  In the JSON it is defined like this:

"type": {
                        "class": "H5T_STRING", 
                        "charSet": "H5T_CSET_ASCII", 
                        "order": "H5T_ORDER_NONE", 
                        "strPad": "H5T_STR_NULLPAD", 
                        "length": 27
                    },

Which is different than what I had documented.  See: http://h5serv.readthedocs.org/en/latest/Types/index.html#string-types-fixed-length. 

It does match the HDF5/JSON spec though.  Is the first time you've tried converting a json file with a string to HDF5?  I'm surprised it hasn't come up before.

**Comment by hyoklee** [comment]
Thanks for pointing out where problem is. I haven't used h5serv since January 10 and I used *strsize* in my obsolete code so I did not catch it:

https://github.com/HDFGroup/hpd/blob/73cbd66799788e851f7f3d858c937bb853cb0f7e/hpd/h5serv.py

Can you update your code and documentation to match spec?

**Comment by jreadey** [comment]
Ok - code and docs are updated!
The file hmap_100.json converts successfully on EC2.

**Comment by hyoklee** [comment]
Thanks, I can create one, too. Is there an way to optimize jsontoh5? It takes longer than 30+ seconds on this JSON as Aleksandar reported, which I could confirm, too:

https://github.com/HDFGroup/hpd-ws/issues/14

**Comment by jreadey** [comment]
I'm not sure what could be done to speed it up.  The text file get's loaded quickly, it's reading through and writing the HDF5 datasets/attributes that is taking time.  There are about a 1000 datasets/attributes/and groups in the json, so this is about 0.03 sec/object.  What speed would you expect?

**Comment by hyoklee** [comment]
The below is performance data in C which I collect everyday for long term regression testing.
I wish you can run the same test in h5py and compare performance.
If h5py is too slow, I think creating a C version of jsontoh5 will be necessary for HPD to be usable in the future.

```
2015-3-16 19:4:23 10000 groups creating 10000 empty groups 1.8 cheetah 0.892405 2
2015-3-16 19:4:23 200000 groups creating 200000 empty groups 1.8 cheetah 3.92601 2
2015-3-16 19:4:23 1000000 record writing 1000000 compound records 1.8 cheetah 7.2016 2
2015-3-16 19:4:23 add_rec adding a record 1.8 cheetah 2.90983 2
2015-3-16 19:4:28 linear cached dataset write rwrite 10000 columns 1.8 cheetah 3.99857 2
2015-3-16 19:4:28 linear cached dataset read rread 10000 rows 1.8 cheetah 0.106121 2
2015-3-16 19:4:46 source as a subset of destination read 1000000 compound elements 1.8 cheetah 4.95819 2
2015-3-16 19:4:46 destination as a subset of source read 1000000 compound elements 1.8 cheetah 5.0817 2
2015-3-16 19:5:8 free space 10000 groups create and delete 10000 groups 1.8 cheetah 8.98892 2
2015-3-16 19:5:8 free space 85 datasets create and delete 85 datasets 1.8 cheetah 3.83624 2
2015-3-16 19:5:8 free space 200 groups w/ datasets create and delete 200 groups with datasets 1.8 cheetah 2.88496 2
2015-3-16 19:5:11 extend early alloc dset extend 10000 rows 1.8 cheetah 3.01625 2
2015-3-16 19:5:14 elink traversal without EFC open 10 files 1000 times 1.8 cheetah 2.53643 2
2015-3-16 19:5:14 elink traversal with EFC open 10 files 1000 times 1.8 cheetah 0.155053 2
2015-3-16 19:5:22 select 1000 disjoint hyperslabs dset 1000 disjoint hyperslab selections 1.8 cheetah 0.37584 2
2015-3-16 19:5:22 select 10000 disjoint hyperslabs dset 10000 disjoint hyperslab selections 1.8 cheetah 7.8209 2
2015-3-16 19:5:22 select 1000 disjoint hyperslabs dset 1000 disjoint hyperslab selections 1.8 cheetah 0.37584 2
2015-3-16 19:5:22 select 10000 disjoint hyperslabs dset 10000 disjoint hyperslab selections 1.8 cheetah 7.8209 2
2015-3-16 19:5:42 creating attributes create 1000 attributes (50 times) 1.8 cheetah 1.20413 2
2015-3-16 19:5:42 writing attributes write 1000 attributes (50 times) 1.8 cheetah 1.26271 2
2015-3-16 19:5:42 deleting attributes delete 1000 attributes 1.8 cheetah 16.9475 2
2015-3-16 19:10:42 append to 2d dset - 1-unlim-old-x append 1-byte chunk up to 2M bytes 1.8 cheetah 73.14 2
2015-3-16 19:10:42 append to 2d dset - 1-unlim-old-y measure time for appending to 2d dset - 1-unlim-old-y 1.8 cheetah 76.9032 2
2015-3-16 19:10:42 append to 2d dset - 1-unlim-new-x measure time for appending to 2d dset - 1-unlim-new-x 1.8 cheetah 73.0985 2
2015-3-16 19:10:42 append to 2d dset - 1-unlim-new-y measure time for appending to 2d dset - 1-unlim-new-y 1.8 cheetah 77.5239 2
2015-3-16 19:16:21 append to 2d dset - 2-unlim-old-x append 1-byte chunk up to 2M bytes 1.8 cheetah 71.6299 2
2015-3-16 19:16:21 append to 2d dset - 2-unlim-old-y measure time for appending to 2d dset - 2-unlim-old-y 1.8 cheetah 75.1732 2
2015-3-16 19:16:21 append to 2d dset - 2-unlim-old-xy measure time for appending to 2d dset - 2-unlim-old-xy 1.8 cheetah 21.7608 2
2015-3-16 19:16:21 append to 2d dset - 2-unlim-new-x measure time for appending to 2d dset - 2-unlim-new-x 1.8 cheetah 72.6429 2
2015-3-16 19:16:21 append to 2d dset - 2-unlim-new-y measure time for appending to 2d dset - 2-unlim-new-y 1.8 cheetah 75.6385 2
2015-3-16 19:16:21 append to 2d dset - 2-unlim-new-xy measure time for appending to 2d dset - 2-unlim-new-xy 1.8 cheetah 21.7612 2

```
