### ISSUE TITLE
h5tojson.py can't convert TES-Aura_L2-O3-Nadir_r0000011015_F05_07.he5 file.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/h5serv#44]
You can download the test file from here:

http://www.hdfgroup.uiuc.edu/ftp/pub/outgoing/NASAHDF/TES-Aura_L2-O3-Nadir_r0000011015_F05_07.he5

```
python h5tojson.py -d /mnt/ftp/pub/outgoing/NASAHDF/TES-Aura_L2-O3-Nadir_r0000011015_F05_07.he5 > /Users/hyoklee/src/hpd/TES-Aura_L2-O3-Nadir_r0000011015_F05_07.json
Traceback (most recent call last):
  File "h5tojson.py", line 236, in <module>
    main()
  File "h5tojson.py", line 233, in main
    dumper.dumpFile()    
  File "h5tojson.py", line 188, in dumpFile
    self.dumpDatasets()
  File "h5tojson.py", line 154, in dumpDatasets
    item = self.dumpDataset(uuid)
  File "h5tojson.py", line 143, in dumpDataset
    value = self.db.getDatasetValuesByUuid(uuid)
  File "../server/hdf5db.py", line 1281, in getDatasetValuesByUuid
    values = dset[slices].tolist()  # just dump to list
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2405)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2362)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 467, in __getitem__
    self.id.read(mspace, fspace, arr, mtype)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2405)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2362)
  File "h5py/h5d.pyx", line 175, in h5py.h5d.DatasetID.read (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/h5d.c:3004)
  File "h5py/_proxy.pyx", line 150, in h5py._proxy.dset_rw (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_proxy.c:1777)
  File "h5py/_proxy.pyx", line 319, in h5py._proxy.needs_bkg_buffer (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_proxy.c:3304)
  File "h5py/_proxy.pyx", line 316, in h5py._proxy.needs_bkg_buffer (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_proxy.c:3243)
KeyError: 'Conversion function not found (No appropriate function for conversion path)'
```

**Comment by jreadey** [comment]
The problematic dataset is '/HDFEOS/SWATHS/O3NadirSwath/Data Fields/UTCTime'.  This may be an h5py issue, I get the same error if I try to read the dataset in ipython.

**Comment by jreadey** [comment]
Joe, can you create/find an example HDF5 file with vlen string and NULLTERM strpad?

**Comment by hyoklee** [comment]
Please ask HDF5 library team or help desk, not me.

**Comment by jreadey** [comment]
Doesn't look like a library issue.  I've submitted an h5py issue: https://github.com/h5py/h5py/issues/565.

**Comment by hyoklee** [comment]
Thanks for submitting issue to h5py.
