### ISSUE TITLE
Docs - Please add tutorials

### ISSUE THREAD

**Issue by ahalota** [HDFGroup/h5serv#73]
I'm having some trouble on set-up and was disappointed to find a placeholder under the tutorials section. Would be really helpful to have a quick walkthrough on making some basic requests.

**Comment by jreadey** [comment]
Sorry we haven't gotten around to this yet.
For now, looking through the test/integ test cases should be a good start for seeing how the http api works.

**Comment by vsisl** [comment]
I see that his is a very old thread... However, I totally agree with @ahalota that some server set-up tutorial (even a very brief one)  would be EXTREMELY useful.

I have been trying to set-up my first h5server for last few days and  at this point I am getting hopeless. Using both docker and manual installation, I cannot get data from the server even though the server is running and I am able to get some responses. 

I wonder if it is an issue of the server installation itself, if it is an issue of h5pyd (which I use to execute requests), or if it has something to do with server set-up (e.g. authentication).  

As I said, even a minimal tutorial would be very helpful and appreciated.

**Comment by seb5g** [comment]
I completely agree, I'm at a loss of where to start to debug even the test suite...

**Comment by vsisl** [comment]
@seb5g have a look at [Issue #128](https://github.com/HDFGroup/h5serv/issues/128) it might be helpful.

**Comment by seb5g** [comment]
Thanks, that actually helps!!

Sébastien Weber

**Comment by jreadey** [comment]
Hopefully the install docs for HSDS are an improvement.  Now that HSDS supports posix storage, I'd recommend using HSDS over h5serv.  Here's the doc for the HSDS Posix install: https://github.com/HDFGroup/hsds/blob/master/docs/docker_install.md.

**Comment by vsisl** [comment]
@jreadey does that mean that I can replace h5serv by HSDS and host the file server locally? (instead of cloud hosting like AWS)

**Comment by seb5g** [comment]
@jreadey , I just installed the HSDS posix docker image and I'm up and running until the integration tests. They fail... It seems there's an issue with the writing of the file. I tried the postinstall config and noticed the step:
5 Create a test folder on HSDS: $ hstouch -u test_user1 -p <passwd> /home/test_user1/test/ 
is missing the entrypoint (no error if I add it). But then on step 6 the loading of the h5 file is not going well (even if I add the correct entry point):

`(base) weber@weber-Precision-WorkStation-T3400:~/hsds$ hsload -v -e http://hsds.hdf.test  -u test_user1 -p test tall.h5 /home/test_user1/test/
2020-03-18 00:28:29,403 hsload.py:316 Error creating file /home/test_user1/test/tall.h5: HTTPConnectionPool(host='hsds.hdf.test', port=80): Max retries exceeded with url: /?domain=%2Fhome%2Ftest_user1%2Ftest%2Ftall.h5 (Caused by ResponseError('too many 500 error responses'))
(base) weber@weber-Precision-WorkStation-T3400:~/hsds$ 
`
I'm wondering: 

- should not step 5 create in my ROOT_DIR the proper folders /home/test_user1/test/ 

- is the home folder, the ROOT_DIR folder in that case?

Here is the failing test:
`domain_test
Traceback (most recent call last):
  File "domain_test.py", line 1118, in <module>
    unittest.main()
  File "/home/weber/miniconda3/lib/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/home/weber/miniconda3/lib/python3.7/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/home/weber/miniconda3/lib/python3.7/unittest/main.py", line 156, in createTests
    self.test = self.testLoader.loadTestsFromModule(self.module)
  File "/home/weber/miniconda3/lib/python3.7/unittest/loader.py", line 124, in loadTestsFromModule
    tests.append(self.loadTestsFromTestCase(obj))
  File "/home/weber/miniconda3/lib/python3.7/unittest/loader.py", line 93, in loadTestsFromTestCase
    loaded_suite = self.suiteClass(map(testCaseClass, testCaseNames))
  File "/home/weber/miniconda3/lib/python3.7/unittest/suite.py", line 24, in __init__
    self.addTests(tests)
  File "/home/weber/miniconda3/lib/python3.7/unittest/suite.py", line 57, in addTests
    for test in tests:
  File "domain_test.py", line 25, in __init__
    helper.setupDomain(self.base_domain, folder=True)
  File "/home/weber/hsds/tests/integ/helper.py", line 149, in setupDomain
    raise ValueError(f"Unexpected put domain error: {rsp.status_code}")
ValueError: Unexpected put domain error: `500`

Thanks for your input
Seb5g
